# Generated by Django 3.1.2 on 2020-10-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201022_0836'),
        ('users', '0003_auto_20201022_1206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users_products_likes',
            new_name='Like',
        ),
        migrations.RemoveField(
            model_name='user',
            name='like',
        ),
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(through='users.Like', to='products.Product'),
        ),
    ]
