# Generated by Django 3.1.2 on 2020-10-23 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201022_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
