# Generated by Django 3.1.2 on 2020-10-21 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'age_ranges',
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
            ],
            options={
                'db_table': 'review_images',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'scores',
            },
        ),
        migrations.CreateModel(
            name='SkinShade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_shade', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'skin_shades',
            },
        ),
        migrations.CreateModel(
            name='SkinType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'skin_types',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=45)),
                ('user_name', models.CharField(max_length=10)),
                ('review_date', models.DateField(auto_now_add=True)),
                ('comment', models.TextField(max_length=200)),
                ('age_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.agerange')),
                ('review_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.reviewimage')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.score')),
                ('skin_shade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.skinshade')),
                ('skin_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.skintype')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
