# Generated by Django 3.1.2 on 2020-10-22 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
        migrations.RenameModel(
            old_name='ProductsApplyOn',
            new_name='ProductApplyOn',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AlterModelTable(
            name='applyon',
            table='apply_ons',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='productapplyon',
            table='products_apply_ons',
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.color'),
        ),
    ]
