# Generated by Django 3.1.2 on 2020-10-23 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201022_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AlterModelTable(
            name='color',
            table='colors',
        ),
    ]
