# Generated by Django 3.1.2 on 2020-10-27 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201024_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.URLField(max_length=1000)),
                ('product_image', models.URLField(max_length=1000)),
                ('model_image', models.URLField(max_length=1000)),
                ('detail1_image', models.URLField(max_length=1000)),
                ('detial2_image', models.URLField(max_length=1000)),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'products_colors',
            },
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.AddField(
            model_name='image',
            name='product_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcolor'),
        ),
    ]
