# Generated by Django 3.1.2 on 2020-10-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201027_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='logo_image',
        ),
    ]
