# Generated by Django 3.1.2 on 2020-10-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_image_logo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='detial2_image',
            new_name='detail2_image',
        ),
    ]
